name: xwallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  simple_gradient_text: 1.2.4
  animated_flip_counter: ^0.2.5
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  country_picker: ^2.0.19
  envied: ^0.3.0+3
  animated_rotation: ^2.0.0
  qr_flutter: ^4.1.0
  animate_gradient: ^0.0.2+1
  gradient_borders: ^1.0.0
  image_picker: ^1.0.1
  google_fonts: ^5.1.0
  flutter_animated_dialog: ^2.0.1
  share: ^2.0.1
  flutter_svg: ^2.0.7
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.0.15
  path: ^1.8.3
  provider: ^6.0.1
  dot_navigation_bar: ^1.0.2
  line_icons: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - lib\assets\SwapButton.svg
      - lib\assets\SendButton.svg
      - lib\assets\RecieveButton.svg
      - lib\assets\bitcoin-btc-logo.svg
      - lib\assets\bnb-bnb-logo.svg
      - lib\assets\ethereum-eth-logo.svg
      - lib\assets\tether-usdt-logo.svg
      - lib\assets\usd-coin-usdc-logo.svg
      - lib\assets\xrp-xrp-logo.svg
      - lib\assets\cardano-ada-logo.svg   
      - lib\assets\dogecoin-doge-logo.svg
      - lib\assets\solana-sol-logo.svg
      - lib\assets\tron-trx-logo.svg
      - lib\assets\polygon-matic-logo.svg
      - lib\assets\polkadot-new-dot-logo.svg
      - lib\assets\avalanche-avax-logo.svg
      - lib\assets\bitcoin-cash-bch-logo.svg
      - lib\assets\wrapped-bitcoin-wbtc-logo.svg
      - lib\assets\toncoin-ton-logo.svg
      - lib\assets\multi-collateral-dai-dai-logo.svg
      - lib\assets\shiba-inu-shib-logo.svg
      - lib\assets\stellar-xlm-logo.svg
      - lib\assets\litecoin-ltc-logo.svg


   
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
    - family: Gratesque
      fonts:
        - asset: lib/fonts/DarkerGrotesque-VariableFont_wght.ttf
    - family: Manjari
      fonts: 
        - asset: fonts/Manjari-Regular.ttf     
        - asset: fonts/Manjari-Bold.ttf
        - asset: fonts/Manjari-Thin.ttf
uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
 